# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
