# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20161227_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image_url',
            new_name='image_name',
        ),
    ]
